apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-j6sx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-j6sx@sha256:ebe8a39de96b16c66d68ffcd9dd0aad1f81e412955ac250b2a39c2602296fc27
        name: my-nodejs
        resources: {}
status: {}
